// Content collections: every service, engagement model, proof card, FAQ entry
// and repo card on the site is data here. Pages render from these; see TEMPLATE.md.
import { defineCollection } from 'astro:content';
import { file, glob } from 'astro/loaders';
import { z } from 'astro/zod';

/** The two states a service may carry. Never add a third without a legend entry. */
const serviceStatus = z.enum(['available', 'requires-scoping']);

const link = z.object({ label: z.string(), href: z.url() });

const services = defineCollection({
  // One Markdown file per service. The front matter is the data; an optional body
  // becomes extra prose on the service's own page (/services/<id>).
  loader: glob({ pattern: '*.{md,mdx}', base: './src/content/services' }),
  schema: z.object({
    name: z.string(),
    order: z.number(),
    status: serviceStatus,
    /** One line: the outcome the client gets, not what the consultant does. */
    oneLine: z.string(),
    /** 2-3 sentences of buyer outcome, shown on the service page. */
    summary: z.string(),
    /** What 'requires-scoping' means, honestly. Empty for available services. */
    statusNote: z.string().default(''),
    duration: z.string(),
    deliverables: z.array(z.string()),
    /** Evidence anchors: public repo names or anonymized category phrases. */
    evidence: z.array(z.string()),
    vendors: z.array(z.string()).default([]),
    links: z.array(link).default([]),
    /** Ids of related services. */
    related: z.array(z.string()).default([]),
  }),
});

const engagements = defineCollection({
  loader: file('src/content/engagements.yaml'),
  schema: z.object({
    name: z.string(),
    order: z.number(),
    duration: z.string(),
    deliverable: z.string(),
    prerequisites: z.string(),
  }),
});

const proof = defineCollection({
  loader: file('src/content/proof.yaml'),
  schema: z.object({
    name: z.string(),
    order: z.number(),
    /** The dated number the card carries; sourced from the repo or paper. */
    badge: z.string(),
    /** Where the number comes from, dated. */
    source: z.string(),
    url: z.url().optional(),
    note: z.string(),
  }),
});

const faq = defineCollection({
  loader: file('src/content/faq.yaml'),
  schema: z.object({ q: z.string(), a: z.string(), order: z.number() }),
});

/** The Open Source grid. Generated by /root/portfolio-sync daily; do not edit by hand. */
const repos = defineCollection({
  loader: file('src/content/repos.yaml'),
  schema: z.object({
    name: z.string(),
    url: z.string(),
    description: z.string(),
    lang: z.string().optional(),
    langColor: z.string().optional(),
    stars: z.number().optional(),
    forks: z.union([z.number(), z.literal('fork')]).optional(),
    /** Service-line grouping: network | agents | inference | method | applied. */
    category: z.enum(['network', 'agents', 'inference', 'method', 'applied']),
    pinned: z.boolean().default(false),
    order: z.number(),
  }),
});

export const collections = { services, engagements, proof, faq, repos };
